#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# DocMaster — dm-generate-manifest.sh
# Generates /opt/docmaster/vault/manifest.lock
#
# The manifest is the authoritative record of exactly what is installed on the
# appliance. It is written once at the end of Phase 1 and is read-only after.
# It is used by:
#   - Phase 8 Packer build — to verify image matches expected config
#   - dm-sentinel diagnostics — to confirm environment has not drifted
#   - Field support — to identify the exact installed version
#
# Run as: root (during install) or dmuser (for re-verification)
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

readonly DM_USER="dmuser"
readonly DM_GROUP="docgroup"
readonly DM_HOME="/opt/docmaster"
readonly MANIFEST_FILE="${DM_HOME}/vault/manifest.lock"
readonly OLLAMA_BIN="${DM_HOME}/bin/ollama"
readonly PG_VERSION="16"

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

# ── Build manifest content ─────────────────────────────────────────────────────
generate() {
    local ts
    ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    cat << EOF
# ═══════════════════════════════════════════════════════════════════════════════
# DocMaster Appliance Manifest
# ═══════════════════════════════════════════════════════════════════════════════
# Generated:   ${ts}
# Node:        $(hostname 2>/dev/null || echo "unknown")
# Purpose:     Authoritative record of Phase 1 installed state
# Permissions: 440 (read-only) — dmuser:docgroup
# DO NOT EDIT THIS FILE — Regenerate with dm-generate-manifest.sh if needed
# ═══════════════════════════════════════════════════════════════════════════════

## SECTION: OS Release
$(cat /etc/os-release 2>/dev/null || echo "ERROR: /etc/os-release not found")

## SECTION: Kernel
$(uname -r 2>/dev/null)

## SECTION: Architecture
$(uname -m 2>/dev/null)

## SECTION: Hostname
$(hostname 2>/dev/null)

## SECTION: Timezone
$(timedatectl show --property=Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo "unknown")

## SECTION: Locale
$(locale 2>/dev/null | head -5 || echo "unknown")

## SECTION: Python 3.12
$(python3.12 --version 2>/dev/null || python3 --version 2>/dev/null || echo "NOT INSTALLED")

## SECTION: Node.js
$(node --version 2>/dev/null || echo "NOT INSTALLED")

## SECTION: npm
$(npm --version 2>/dev/null || echo "NOT INSTALLED")

## SECTION: PostgreSQL
$(psql --version 2>/dev/null || echo "NOT INSTALLED")
Package: $(dpkg -l "postgresql-${PG_VERSION}" 2>/dev/null | grep '^ii' | awk '{print $2, $3}' || echo "not found")
pgvector: $(dpkg -l "*pgvector*" 2>/dev/null | grep '^ii' | awk '{print $2, $3}' || echo "not found")

## SECTION: Redis
$(redis-server --version 2>/dev/null || echo "NOT INSTALLED")

## SECTION: Tesseract
$(tesseract --version 2>/dev/null | head -3 || echo "NOT INSTALLED")
Tessdata:
$(ls /usr/share/tessdata/*.traineddata 2>/dev/null | xargs -I{} basename {} .traineddata | sort | tr '\n' ' ' || echo "none")

## SECTION: Ollama
Binary: $([ -f "${OLLAMA_BIN}" ] && echo "${OLLAMA_BIN}" || echo "NOT FOUND")
Version: $(sudo -u "${DM_USER}" "${OLLAMA_BIN}" --version 2>/dev/null || "${OLLAMA_BIN}" --version 2>/dev/null || echo "NOT INSTALLED")

## SECTION: Ollama Models
$(
    if sudo -u "${DM_USER}" \
        OLLAMA_HOST=127.0.0.1:11434 \
        OLLAMA_MODELS="${DM_HOME}/models" \
        "${OLLAMA_BIN}" list 2>/dev/null; then
        true
    else
        echo "Ollama not running — listing model files:"
        find "${DM_HOME}/models" -name "*.gguf" -o -name "manifest" 2>/dev/null | head -20 || echo "none"
    fi
)

## SECTION: Key System Packages
$(dpkg -l \
    poppler-utils imagemagick ghostscript ffmpeg \
    postfix samba hylafax-server \
    apparmor apparmor-utils \
    tesseract-ocr ufw chrony \
    libheif-dev libgomp1 libopenblas-dev \
    2>/dev/null | grep '^ii' | awk '{printf "%-40s %s\n", $2, $3}' || echo "none")

## SECTION: UFW Rules
$(ufw status verbose 2>/dev/null || echo "UFW not active")

## SECTION: systemd Services (DocMaster)
$(systemctl list-unit-files 'dm-*.service' 2>/dev/null || echo "none")

## SECTION: Directory Permissions
$(stat -c "%n  owner=%U:%G  mode=%a" \
    "${DM_HOME}" \
    "${DM_HOME}/bin" \
    "${DM_HOME}/config" \
    "${DM_HOME}/core" \
    "${DM_HOME}/vault" \
    "${DM_HOME}/tmp" \
    "${DM_HOME}/data" \
    "${DM_HOME}/queue" \
    "${DM_HOME}/ingest" \
    "${DM_HOME}/logs" \
    "${DM_HOME}/backups" \
    "${DM_HOME}/models" \
    "${DM_HOME}/www" \
    2>/dev/null || echo "some directories not found")

## SECTION: Symlink
$(ls -la /opt/docmaster 2>/dev/null || echo "symlink not found")

## SECTION: Manifest File Checksums (set after writing)
# SHA256 hash of this manifest file is appended at the bottom of this file.
# Verify with: sha256sum -c <(tail -1 manifest.lock | awk '{print $2, "manifest.lock"}')
# Note: the hash line itself is excluded from the checksum.

## GENERATED: ${ts}
EOF
}

# ── Write manifest ─────────────────────────────────────────────────────────────
log "Generating manifest..."

# Ensure vault dir exists with correct permissions
mkdir -p "${DM_HOME}/vault"
chown "${DM_USER}:${DM_GROUP}" "${DM_HOME}/vault" 2>/dev/null || true
chmod 700 "${DM_HOME}/vault" 2>/dev/null || true

# Generate content
generate > "${MANIFEST_FILE}"

# Compute SHA-256 of the content (excluding the hash line itself)
SHA256=$(sha256sum "${MANIFEST_FILE}" | awk '{print $1}')
echo "" >> "${MANIFEST_FILE}"
echo "## SHA256: ${SHA256}" >> "${MANIFEST_FILE}"

# Lock down
chown "${DM_USER}:${DM_GROUP}" "${MANIFEST_FILE}"
chmod 440 "${MANIFEST_FILE}"

log "Manifest written: ${MANIFEST_FILE}"
log "SHA-256: ${SHA256}"
log "Mode: 440 (read-only), owner: ${DM_USER}:${DM_GROUP}"
